import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, rm } from 'node:fs/promises';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import * as Y from 'yjs';
import WebSocket from 'ws';
import { createStudioServer } from '../server.mjs';
import { issueStudioToken } from '../../shared/studio-token.mjs';
import { webpSize } from '../media.mjs';
import { vector } from '../store.mjs';
import { prepareTemplate } from '../template.mjs';

const picture = Buffer.from('UklGRi4AAABXRUJQVlA4ICIAAABwAQCdASoMAAgAAUAiJYgCdAF1AAD+8dvAB/i37R/e2FAA', 'base64');

test('shared image bank protects uploads, preserves concurrent text and comments, rejects stale choices and survives restart', async t => {
  const directory = await mkdtemp(join(tmpdir(), 'althea-media-'));
  const options = { port: 0, secret: 'studio-media-test-secret-over-thirty-two', allowed: ['juho', 'julia'], origins: ['https://editor.example'], login: { check() {} }, dataDir: directory };
  let server = await createStudioServer(options);
  t.after(async () => { await server.close(); await rm(directory, { recursive: true }); });
  const token = issueStudioToken({ login: 'julia', name: 'Julia' }, options.secret);
  const headers = { authorization: `Bearer ${token}`, origin: options.origins[0] };
  let base = `http://127.0.0.1:${server.port}`;
  const get = async path => (await fetch(base + path, { headers })).json();
  const post = (path, body) => fetch(base + path, { method: 'POST', headers: { ...headers, 'content-type': 'application/json' }, body: JSON.stringify(body) });
  assert.equal((await fetch(base + '/api/media')).status, 401);
  assert.equal((await fetch(base + '/api/media', { headers: { ...headers, origin: 'https://other.example' } })).status, 403);
  const bank = await get('/api/media'); assert.ok(bank.images.length >= 8);
  const slot = bank.slots.find(item => item.kind === 'background'); assert.equal(slot.label, 'Yläosan taustakuva');
  const socket = new WebSocket(base.replace('http', 'ws') + '/sync/althea-uusi', ['althea-auth.' + token], { origin: options.origins[0] });
  await new Promise((resolve, reject) => { socket.once('open', resolve); socket.once('error', reject); });
  socket.send(Buffer.from([6]));
  const notice = new Promise(resolve => socket.on('message', bytes => { if (bytes[0] === 6) resolve(); }));
  const uploaded = await fetch(base + '/api/media-upload?name=Testikuva.png', { method: 'POST', headers: { ...headers, 'content-type': 'image/webp' }, body: picture });
  assert.equal(uploaded.status, 200); const { entry } = await uploaded.json();
  await Promise.race([notice, new Promise((_, reject) => { const timeout = setTimeout(() => reject(new Error('Missing shared library notification')), 3000); timeout.unref(); })]);
  socket.close();
  const duplicate = await fetch(base + '/api/media-upload?name=Kopio.webp', { method: 'POST', headers, body: picture });
  assert.equal((await duplicate.json()).duplicate, true);
  assert.equal((await get('/api/media')).images.length, bank.images.length + 1);
  const file = await fetch(base + '/api/media-file/' + entry.id, { headers });
  assert.equal(file.headers.get('content-type'), 'image/webp'); assert.deepEqual(Buffer.from(await file.arrayBuffer()), picture);
  assert.equal((await fetch(base + '/api/media-file/' + entry.id)).status, 401);
  assert.equal((await fetch(base + '/api/media-file/' + '0'.repeat(64), { headers })).status, 404);
  const initial = server.store.export();
  assert.equal((await (await post('/api/export', { vector: initial.vector })).json()).assets.length, 0);
  const field = server.store.manifest.fields[0].id;
  const candidate = new Y.Doc(); Y.applyUpdate(candidate, Y.encodeStateAsUpdate(server.store.doc));
  const text = candidate.getXmlFragment(field).get(0).get(0); text.insert(text.length, ' Julian samanaikainen muutos.');
  candidate.getMap('comments').set('image-comment', { fieldId: field, body: 'Tekstikommentti säilyy.', author: 'Julia', createdAt: new Date().toISOString(), resolved: false });
  server.store.apply(Y.encodeStateAsUpdate(candidate, Y.encodeStateVector(server.store.doc)), null, { sub: 'julia', name: 'Julia' }); candidate.destroy();
  const latest = JSON.stringify(server.store.fields()), history = server.store.fieldHistory(field);
  const assignment = { nodeId: slot.id, imageHash: slot.imageHash, mediaId: entry.id, alt: 'Vihreä testikuva', position: '50% 20%' };
  assert.equal((await post('/api/media-assign', assignment)).status, 200);
  assert.equal(JSON.stringify(server.store.fields()), latest); assert.deepEqual(server.store.fieldHistory(field), history);
  assert.equal(server.store.comments.get('image-comment').body, 'Tekstikommentti säilyy.');
  let nextBank = await get('/api/media');
  const nextSlot = nextBank.slots.find(item => item.id === slot.id);
  assert.equal(nextSlot.src, entry.path); assert.equal(nextSlot.position, '50% 20%');
  assert.deepEqual(nextBank.slots.filter(item => item.id !== slot.id), bank.slots.filter(item => item.id !== slot.id));
  assert.equal((await post('/api/media-assign', assignment)).status, 409);
  assert.equal((await post('/api/media-assign', { ...assignment, imageHash: nextSlot.imageHash, position: 'url(javascript:x)' })).status, 400);
  assert.equal((await post('/api/media-assign', { ...assignment, imageHash: nextSlot.imageHash, mediaId: '../../secret' })).status, 404);
  assert.equal((await post('/api/export', { vector: initial.vector })).status, 409);
  const snapshot = await (await post('/api/export', { vector: vector(server.store.doc) })).json();
  assert.deepEqual(snapshot.assets, [{ path: entry.path, digest: entry.id, content: picture.toString('base64') }]);
  assert.equal(prepareTemplate(snapshot.html).manifest.layoutHash, snapshot.layoutHash);
  assert.ok(snapshot.html.includes('Julian samanaikainen muutos.'));
  assert.equal((await fetch(base + '/api/media-upload', { method: 'POST', headers, body: '<svg onload="alert(1)"/>' })).status, 400);
  assert.equal((await fetch(base + '/api/media-upload', { method: 'POST', headers, body: Buffer.alloc(2 * 1024 * 1024 + 1) })).status, 413);
  await server.close(); server = await createStudioServer(options); base = `http://127.0.0.1:${server.port}`;
  nextBank = await get('/api/media');
  assert.equal(nextBank.images.length, bank.images.length + 1); assert.deepEqual(nextBank.slots.find(item => item.id === slot.id), nextSlot);
  assert.equal(JSON.stringify(server.store.fields()), latest); assert.equal(server.store.comments.size, 1);
  assert.deepEqual(server.media.read(entry.id), picture);
});

test('image validator rejects oversized dimensions, animation and truncated or executable payloads', () => {
  assert.deepEqual(webpSize(picture), { width: 12, height: 8 });
  const extended = Buffer.alloc(18); extended.write('VP8X'); extended.writeUInt32LE(10, 4);
  extended[8] = 0x20; extended.writeUIntLE(11, 12, 3); extended.writeUIntLE(7, 15, 3);
  const profile = Buffer.alloc(12); profile.write('ICCP'); profile.writeUInt32LE(4, 4); profile.write('test', 8);
  const colorPicture = Buffer.concat([picture.subarray(0, 12), extended, profile, picture.subarray(12)]);
  colorPicture.writeUInt32LE(colorPicture.length - 8, 4);
  assert.deepEqual(webpSize(colorPicture), { width: 12, height: 8 });
  const animated = Buffer.from(colorPicture); animated[20] |= 0x02; assert.throws(() => webpSize(animated), /Liikkuvia/);
  const large = Buffer.from(picture); large.writeUInt16LE(4096, 26); assert.throws(() => webpSize(large), /liian suuri/);
  assert.throws(() => webpSize(picture.subarray(0, -1)), /kelvollinen/);
  assert.throws(() => webpSize(Buffer.from('<svg/>')), /kelvollinen/);
  const executable = Buffer.from(picture); executable.write('EXIF', 12); assert.throws(() => webpSize(executable), /ei tueta/);
});

test('image removal is shared and recoverable, protects current use, and preserves text and history through restart', async t => {
  const directory = await mkdtemp(join(tmpdir(), 'althea-media-delete-'));
  const options = { port: 0, secret: 'studio-media-test-secret-over-thirty-two', allowed: ['juho', 'julia'], origins: ['https://editor.example'], login: { check() {} }, dataDir: directory };
  let server = await createStudioServer(options), base = `http://127.0.0.1:${server.port}`;
  t.after(async () => { await server.close(); await rm(directory, { recursive: true }); });
  const headers = { authorization: `Bearer ${issueStudioToken({ login: 'julia', name: 'Julia' }, options.secret)}`, origin: options.origins[0] };
  const get = async path => (await fetch(base + path, { headers })).json();
  const post = (path, body) => fetch(base + path, { method: 'POST', headers: { ...headers, 'content-type': 'application/json' }, body: JSON.stringify(body) });
  const bank = await get('/api/media'), original = bank.images.find(image => bank.slots.some(slot => slot.src === image.path));
  const uploaded = await fetch(base + '/api/media-upload?name=Poiston-testikuva.png', { method: 'POST', headers, body: picture });
  const { entry } = await uploaded.json();
  const field = server.store.manifest.fields[0].id;
  const candidate = new Y.Doc(); Y.applyUpdate(candidate, Y.encodeStateAsUpdate(server.store.doc));
  const text = candidate.getXmlFragment(field).get(0).get(0); text.insert(text.length, ' Samanaikainen tekstimuutos.');
  candidate.getMap('comments').set('delete-comment', { fieldId: field, body: 'Kommentti säilyy.', author: 'Julia', createdAt: new Date().toISOString(), resolved: false });
  server.store.apply(Y.encodeStateAsUpdate(candidate, Y.encodeStateVector(server.store.doc)), null, { sub: 'julia', name: 'Julia' }); candidate.destroy();
  const fields = JSON.stringify(server.store.fields()), history = server.store.fieldHistory(field);
  assert.equal((await fetch(base + '/api/media-delete', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ mediaId: entry.id }) })).status, 401);
  assert.equal((await fetch(base + '/api/media-delete', { method: 'POST', headers: { ...headers, origin: 'https://other.example' }, body: JSON.stringify({ mediaId: entry.id }) })).status, 403);
  assert.equal((await post('/api/media-delete', { mediaId: '../../secret' })).status, 404);
  assert.equal((await post('/api/media-restore', { mediaId: '0'.repeat(64) })).status, 404);
  assert.equal((await post('/api/media-delete', { mediaId: original.id })).status, 409);
  const socket = new WebSocket(base.replace('http', 'ws') + '/sync/althea-uusi', ['althea-auth.' + issueStudioToken({ login: 'juho', name: 'Juho' }, options.secret)], { origin: options.origins[0] });
  await new Promise((resolve, reject) => { socket.once('open', resolve); socket.once('error', reject); });
  t.after(() => socket.terminate());
  socket.send(Buffer.from([6]));
  const notice = new Promise(resolve => socket.on('message', bytes => { if (bytes[0] === 6) resolve(); }));
  assert.equal((await post('/api/media-delete', { mediaId: entry.id })).status, 200);
  await Promise.race([notice, new Promise((_, reject) => { const timeout = setTimeout(() => reject(new Error('Missing image removal notification')), 3000); timeout.unref(); })]);
  socket.close();
  let next = await get('/api/media');
  assert.equal(next.images.length, bank.images.length); assert.equal(next.deletedImages.length, 1);
  assert.equal(next.deletedImages[0].deletedBy, 'Julia');
  const slot = bank.slots[0], assignment = { nodeId: slot.id, imageHash: slot.imageHash, mediaId: entry.id, alt: 'Testikuva', position: '50% 50%' };
  assert.equal((await post('/api/media-assign', assignment)).status, 409);
  assert.deepEqual(Buffer.from(await (await fetch(base + '/api/media-file/' + entry.id, { headers })).arrayBuffer()), picture);
  assert.equal((await post('/api/media-restore', { mediaId: entry.id })).status, 200);
  assert.equal((await post('/api/media-assign', assignment)).status, 200);
  // A stale bank view cannot delete an image another editor just put on the page.
  assert.equal((await post('/api/media-delete', { mediaId: entry.id })).status, 409);
  next = await get('/api/media'); assert.equal(next.images.find(image => image.id === entry.id).inUse, true);
  const currentSlot = next.slots.find(item => item.id === slot.id), priorImage = bank.images.find(image => image.path === slot.src);
  assert.equal((await post('/api/media-assign', { ...assignment, imageHash: currentSlot.imageHash, mediaId: priorImage.id })).status, 200);
  assert.equal((await post('/api/media-delete', { mediaId: entry.id })).status, 200);
  await server.close(); server = await createStudioServer(options); base = `http://127.0.0.1:${server.port}`;
  next = await get('/api/media'); assert.equal(next.deletedImages.length, 1); assert.equal(next.images.some(image => image.id === entry.id), false);
  assert.equal(JSON.stringify(server.store.fields()), fields); assert.deepEqual(server.store.fieldHistory(field), history);
  assert.equal(server.store.comments.get('delete-comment').body, 'Kommentti säilyy.');
  assert.equal((await post('/api/media-restore', { mediaId: entry.id })).status, 200);
  // Original site assets are removable too; their tombstones survive template scans.
  next = await get('/api/media');
  for (const used of next.slots.filter(item => item.src === original.path)) {
    assert.equal((await post('/api/media-assign', { nodeId: used.id, imageHash: used.imageHash, mediaId: entry.id, alt: used.alt, position: used.position })).status, 200);
  }
  assert.equal((await post('/api/media-delete', { mediaId: original.id })).status, 200);
  await server.close(); server = await createStudioServer(options); base = `http://127.0.0.1:${server.port}`;
  next = await get('/api/media'); assert.equal(next.images.some(image => image.id === original.id), false);
  assert.equal(next.deletedImages.some(image => image.id === original.id), true);
  assert.equal((await post('/api/media-restore', { mediaId: original.id })).status, 200);
  assert.equal(JSON.stringify(server.store.fields()), fields); assert.deepEqual(server.store.fieldHistory(field), history);
});
